name: datasimulation
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - jupyterlab
  - bioconductor-rhtslib
  - python=3.8
  - r-irkernel
  - iqtree
  - r-ape
  - r-phytools
  - r-phangorn
